train:
  train_dir: "data/140k/train"
  test_dir:  "data/140k/val"
  batch_size: 64
  learning_rate: 0.0001
  epochs: 300
  unfreeze_epoch: 25
  patience: 20
  checkpoint_path: "checkpoints/best_model.pth"

eval:
  test_dir: "data/140k/test"
  batch_size: 64
  checkpoint_path: "checkpoints/best_model.pth"

